# Generated by Django 2.2.3 on 2019-08-03 03:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/post_default.jpg', upload_to='static/images/')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 3, 3, 2, 58, 486162, tzinfo=utc), verbose_name='post date')),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/post_default.jpg', upload_to='static/images/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
