# Generated by Django 2.1 on 2019-08-14 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 14, 15, 28, 24, 538396, tzinfo=utc), verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/post_default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.ImageField(default='images/post_default.jpg', upload_to='images/'),
        ),
    ]
