# Generated by Django 2.2.4 on 2019-08-14 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190814_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 14, 15, 45, 21, 746058, tzinfo=utc), verbose_name='post date'),
        ),
    ]
