# Generated by Django 2.2.3 on 2019-08-14 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190803_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 14, 15, 3, 3, 963004, tzinfo=utc), verbose_name='post date'),
        ),
    ]
